name: Deploy to Dev

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      # TODO: use secret instead of var
      SUPABASE_DB_PASSWORD: ${{ vars.DEV_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ vars.DEV_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push 

      - run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
    
  # current test will end up trying to send emails
  # test:
  #   needs: deploy
  #   runs-on: ubuntu-latest

  #   env:
  #     SUPABASE_URL: ${{ vars.DEV_SUPABASE_URL }}
  #     SUPABASE_ANON_KEY: ${{ vars.DEV_SUPABASE_ANON_KEY }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: supabase/setup-cli@v1
  #       with:
  #         version: latest

  #     - uses: denoland/setup-deno@v1
  #       with:
  #         deno-version: v1.x

  #     - run: deno test --allow-all supabase/functions/tests/athlete-progress-report.test.ts
