name: pull-request

on:
  pull_request:
    types: [ opened, edited, synchronize ]

env:
  SUPABASE_URL: ${{ vars.LOCAL_SUPABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase db start

      - name: Run database tests
        run: supabase test db
